'use client';
import React, {useEffect,useState} from 'react';
import {Link,NavLink,Outlet,useLoaderData,useRouteLoaderData,useFetcher,useNavigation,useSearchParams,useRouteError,isRouteErrorResponse,useLocation,useBlocker} from 'react-router-dom';
import {Layers,LogOut,Plus,Bell,Search,ChevronRight,ArrowLeft,Pencil,Trash2,Download,RefreshCw} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {modules,statuses,type Item} from '@/lib/projectsphere/model';
import {fields,type Field} from '@/lib/projectsphere/fields';
const label=(kind:string)=>modules.find(m=>m.key===kind)?.label||kind;
const noCreate=new Set(['audit','reports','notifications','attendance','attempts','settings','comments']);
function useSession(){return useRouteLoaderData('workspace') as any;}
function allowed(session:any,kind:string,action='read'){return !!session?.permissions?.[kind]?.[action];}
function Brand(){return <Link className="brand" to="/overview"><span className="brandmark"><Layers size={20}/></span>ProjectSphere</Link>;}
function Badge({value}:{value:any}){return <span className={'badge '+String(value||'').toLowerCase().replaceAll(' ','-')}>{String(value||'—')}</span>;}
function Feedback({fetcher}:{fetcher:any}){return <>{fetcher.data?.error&&<p className="error my-4" role="alert">{fetcher.data.error}</p>}{fetcher.data?.message&&<p className="my-4 text-emerald-800" role="status">{fetcher.data.message}</p>}</>;}
function Pick({value,onChange,options,label:aria}:{value:any;onChange:(value:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={String(value||'_none')} onValueChange={v=>onChange(v==='_none'?'':String(v))}><SelectTrigger aria-label={aria} className="filter-select"><SelectValue placeholder="Select…"/></SelectTrigger><SelectContent><SelectItem value="_none">Select…</SelectItem>{options.filter(o=>o.value).map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
function Pager({data}:{data:any}){const [query,setQuery]=useSearchParams();return <div className="flex items-center justify-between gap-4 p-5"><span className="text-sm text-slate-500">Page {data.page+1} · {data.items.length} records</span><div className="flex gap-2"><button className="btn small" disabled={data.page===0} onClick={()=>{query.set('page',String(data.page-1));setQuery(query);}}>Previous</button><button className="btn small" disabled={!data.hasNext} onClick={()=>{query.set('page',String(data.page+1));setQuery(query);}}>Next</button></div></div>;}
export function RouteError({message}:{message?:string}){const error=useRouteError();const text=message||(isRouteErrorResponse(error)?String(error.data):error instanceof Error?error.message:'Unable to load this page.');return <div className="p-8"><h1 className="text-2xl mb-4">{isRouteErrorResponse(error)&&error.status===403?'Access restricted':'Unable to open this page'}</h1><p role="alert" className="error">{text}</p><div className="flex gap-4 mt-6"><Link className="btn" to="/overview">Workspace</Link><Link className="btn" to="/login">Sign in</Link></div></div>;}
export function Shell(){const session=useLoaderData() as any;const logout=useFetcher<any>();const nav=useNavigation();const location=useLocation();const page=location.pathname.split('/')[1]||'overview';return <SidebarProvider style={{'--sidebar-width':'236px'} as React.CSSProperties}><Sidebar><SidebarHeader className="px-5 pt-6"><Brand/></SidebarHeader><SidebarContent><SidebarGroup><SidebarMenu><SidebarMenuItem><SidebarMenuButton asChild isActive={page==='overview'}><NavLink to="/overview">Overview</NavLink></SidebarMenuButton></SidebarMenuItem>{modules.filter(m=>allowed(session,m.key)).map(m=><SidebarMenuItem key={m.key}><SidebarMenuButton asChild isActive={page===m.key}><NavLink to={'/'+m.key}>{m.label}</NavLink></SidebarMenuButton></SidebarMenuItem>)}{allowed(session,'users')&&<SidebarMenuItem><SidebarMenuButton asChild isActive={page==='hierarchy'}><NavLink to="/hierarchy">Reporting hierarchy</NavLink></SidebarMenuButton></SidebarMenuItem>}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter className="p-4"><p className="font-semibold truncate">{session.user.title}</p><p className="text-sm text-slate-500 mb-2">{session.roleName}</p><Link className="btn" to="/change-password">Change password</Link><logout.Form method="post" action="/logout"><button className="btn w-full" disabled={logout.state!=='idle'}><LogOut size={16}/>Logout</button></logout.Form><Feedback fetcher={logout}/></SidebarFooter></Sidebar><SidebarInset className="min-w-0 bg-background"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>Workspace</span><ChevronRight size={13}/><b>{label(page)}</b></div><div className="top-actions">{nav.state!=='idle'&&<RefreshCw size={16} className="animate-spin" aria-label="Loading page"/>}{allowed(session,'notifications')&&<Link className="btn ghost small" to="/notifications" aria-label="Notifications"><Bell size={18}/></Link>}<logout.Form method="post" action="/logout"><button className="btn small" disabled={logout.state!=='idle'}><LogOut size={15}/>Logout</button></logout.Form></div></header><main className="pagebody"><Outlet/></main></SidebarInset></SidebarProvider>;}
export function AuthPage({mode}:{mode:'login'|'forgot-password'|'reset-password'|'change-password'}){
 const {configured}=useLoaderData() as any;const fetcher=useFetcher<any>();const [token,setToken]=useState('');const [error,setError]=useState('');const location=useLocation();
 useEffect(()=>{if(mode==='reset-password'){const value=new URLSearchParams(window.location.hash.slice(1)).get('token');if(value)setToken(value);window.history.replaceState(window.history.state,'',window.location.pathname);}},[mode]);
 const changing=mode==='reset-password'||mode==='change-password';const success=!!fetcher.data?.message;
 return <div className={mode==='change-password'?'flex justify-center':'login'}><div className="login-card"><Brand/><h1>{mode==='login'?'Welcome back':mode==='forgot-password'?'Forgot password?':mode==='reset-password'?'Reset password':'Change password'}</h1><p className="subtitle">{mode==='login'?'Sign in to your team workspace.':mode==='forgot-password'?'Enter your account email to request a reset link.':'Use at least 12 characters. You will sign in again after saving.'}</p>{!configured&&<p role="alert" className="error my-4">The workspace service is not configured. Contact your administrator.</p>}
 {!success&&<fetcher.Form method="post" action={location.pathname} onSubmit={e=>{setError('');if(changing){const form=new FormData(e.currentTarget);const password=String(form.get('newPassword'));if(password!==form.get('confirmPassword')||new TextEncoder().encode(password).length>72){e.preventDefault();setError('Passwords must match and contain at most 72 UTF-8 bytes.');}}}}>
 {['login','forgot-password'].includes(mode)&&<label className="field">Email<input className="input" name="email" type="email" autoComplete="username" maxLength={254} required/></label>}
 {['login','change-password'].includes(mode)&&<label className="field">{mode==='login'?'Password':'Current password'}<input className="input" name={mode==='login'?'password':'currentPassword'} type="password" autoComplete="current-password" required/></label>}
 {changing&&<><label className="field">New password<input className="input" name="newPassword" type="password" autoComplete="new-password" minLength={12} maxLength={72} required/></label><label className="field">Confirm password<input className="input" name="confirmPassword" type="password" autoComplete="new-password" minLength={12} maxLength={72} required/></label></>}
 {mode==='reset-password'&&<><input type="hidden" name="token" value={token}/>{!token&&<p className="error">Open your reset link from the email or request a new one.</p>}</>}{error&&<p className="error" role="alert">{error}</p>}<button className="btn primary" disabled={!configured||fetcher.state!=='idle'||mode==='reset-password'&&!token}>{fetcher.state!=='idle'?'Please wait…':mode==='login'?'Sign in':mode==='forgot-password'?'Send reset link':'Save password'}</button></fetcher.Form>}
 <Feedback fetcher={fetcher}/><div className="flex flex-wrap gap-3 mt-6">{mode==='login'?<Link className="btn ghost" to="/forgot-password">Forgot password?</Link>:<Link className="btn ghost" to={mode==='change-password'&&!success?'/overview':'/login'}>{mode==='change-password'&&!success?'Back to workspace':'Back to sign in'}</Link>}{mode==='reset-password'&&<Link className="btn ghost" to="/forgot-password">Request a new link</Link>}</div></div></div>;
}
export function ModulePage(){const {kind,list,current}=useLoaderData() as any;const session=useSession();const [query,setQuery]=useSearchParams();const attendance=useFetcher<any>();const view=query.get('view')||'list';const records=list.items as Item[];return <>
 <div className="pageheading"><div><div className="eyebrow">Workspace</div><h1>{label(kind)}</h1></div>{fields[kind]&&!noCreate.has(kind)&&allowed(session,kind,'create')&&<Link className="btn primary" to={'/'+kind+'/new'}><Plus size={16}/>Create</Link>}</div>
 <form className="toolbar flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);query.set('q',String(form.get('q')||''));query.set('status',String(form.get('status')||''));query.delete('page');setQuery(query);}}><label className="searchbar"><Search size={16}/><input key={query.get('q')} name="q" defaultValue={query.get('q')||''} placeholder="Search by title" aria-label="Search by title"/></label><input key={query.get('status')} className="input max-w-48" name="status" defaultValue={query.get('status')||''} placeholder="Filter by status" aria-label="Status filter"/><button className="btn">Apply filters</button>{['tasks','bugs'].includes(kind)&&<Tabs value={view} onValueChange={v=>{query.set('view',v);setQuery(query);}}><TabsList><TabsTrigger value="list">List</TabsTrigger><TabsTrigger value="board">Board</TabsTrigger></TabsList></Tabs>}</form>
 {kind==='attendance'&&<div className="panel p-6 mb-6"><h2 className="font-semibold mb-3">Your working day</h2><Badge value={current?.status||'Not checked in'}/><attendance.Form method="post" action="/attendance" className="detail-actions">{['check-in','break-start','break-end','check-out'].map(action=><button name="intent" value={action} key={action} className="btn" disabled={attendance.state!=='idle'||!allowed(session,'attendance',action==='check-in'?'create':'update')||(action==='check-in'?!!current?.id:!current?.id||action==='break-start'&&!!current?.breakStart||action==='break-end'&&!current?.breakStart)}>{action.replaceAll('-',' ')}</button>)}</attendance.Form><Feedback fetcher={attendance}/></div>}
 {view==='board'&&['tasks','bugs'].includes(kind)?<><p className="footnote mb-4">Board shows the current page of matching tasks.</p><div className="board">{statuses.map(status=><section className="column" key={status}><div className="column-head">{status}<span>{records.filter(t=>t.status===status).length}</span></div>{records.filter(t=>t.status===status).map(t=><Link key={t.id} className="task-card block" to={'/'+kind+'/'+t.id}><Badge value={t.priority}/><h3>{t.title}</h3><p>{t.labels?.ownerId||'Unassigned'}</p></Link>)}</section>)}</div><Pager data={list}/></>:
 ['projects','courses'].includes(kind)?<><div className="project-grid">{records.map(item=><Link className="project-card" key={item.id} to={'/'+kind+'/'+item.id}><Badge value={item.status}/><h3>{item.title}</h3><p>{item.description}</p><span className="text-sm text-slate-500">{item.dueDate||item.category||'View details'}</span></Link>)}</div>{!records.length&&<p className="empty">No matching records. Create your first record to get started.</p>}<Pager data={list}/></>:
 <div className="panel"><Table><TableHeader><TableRow><TableHead className="pl-5">Title</TableHead><TableHead>Status</TableHead><TableHead>Related to</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{records.map(item=><TableRow key={item.id}><TableCell className="pl-5"><Link className="table-title" to={'/'+kind+'/'+item.id}>{item.title}</Link></TableCell><TableCell><Badge value={item.status}/></TableCell><TableCell>{item.labels?.projectId||item.labels?.ownerId||item.labels?.roleId||'—'}</TableCell><TableCell>{item.score!==undefined?item.score+'%':item.workingHours!==undefined?item.workingHours+'h':item.dueDate||item.position||'—'}</TableCell></TableRow>)}</TableBody></Table>{!records.length&&<p className="empty">No matching records.</p>}<Pager data={list}/></div>}
 </>;}
export function Dashboard(){const session=useSession();const {counts,taskStatuses}=useLoaderData() as any;return <><div className="pageheading"><div><div className="eyebrow">Your workspace at a glance</div><h1>Overview</h1></div></div><div className="stats">{Object.entries(counts).map(([key,value])=><div className="stat" key={key}><div className="stat-top capitalize">{key}</div><div className="stat-value">{String(value)}</div></div>)}</div><div className="panel"><div className="panel-title"><h2>Task distribution</h2>{allowed(session,"tasks")&&<Link className="btn small" to="/tasks">View tasks</Link>}</div><div className="metrics-list">{Object.entries(taskStatuses).map(([status,count])=><div className="metric-line" key={status}><div className="row"><span>{status}</span><span>{String(count)}</span></div><Progress value={counts.tasks?Number(count)/counts.tasks*100:0} className="h-1.5"/></div>)}{!Object.keys(taskStatuses).length&&<p className="empty">No visible tasks yet.</p>}</div></div></>;}
export function Workload(){const data=useLoaderData() as any;return <><div className="pageheading"><h1>Delivery & workload</h1><a className="btn" href="/api/v1/reports/tasks.csv"><Download size={16}/>Export tasks</a></div><div className="panel"><Table><TableHeader><TableRow><TableHead>Employee</TableHead><TableHead>Completed / assigned</TableHead><TableHead>Open hours</TableHead><TableHead>Weekly capacity</TableHead></TableRow></TableHeader><TableBody>{data.items.map((row:any)=><TableRow key={row.id}><TableCell><Link to={'/users/'+row.id}>{row.title}</Link></TableCell><TableCell>{row.completed} / {row.assigned}</TableCell><TableCell>{row.hours}h</TableCell><TableCell>{row.capacity}h · {row.hours>row.capacity?'Over capacity':'Available'}</TableCell></TableRow>)}</TableBody></Table><Pager data={data}/></div><p className="footnote">Open hours include unfinished work. Weekly capacity is a reference, not a dated schedule. Print this page to save a PDF.</p></>;}
export function Hierarchy(){const data=useLoaderData() as any;const session=useSession();return <><div className="pageheading"><h1>Reporting hierarchy</h1><Link className="btn" to={'/hierarchy?reportingTo='+session.user.id}>My direct reports</Link></div><p className="subtitle mb-5">Open a person’s reports to move down the reporting tree.</p><div className="panel">{data.items.map((user:any)=><div className="person-card justify-between" key={user.id}><Link to={'/users/'+user.id}>{user.title}<span className="block text-sm text-slate-500">{user.position}</span></Link><Link className="btn small" to={'/hierarchy?reportingTo='+user.id}>View reports</Link></div>)}{!data.items.length&&<p className="empty">No visible people at this level.</p>}<Pager data={data}/></div></>;}
function ReferenceField({source,context,projectId,value,multiple,onChange,fieldLabel}:{source:string;context:string;projectId?:string;value:any;multiple?:boolean;onChange:(value:any)=>void;fieldLabel:string}){
 const fetcher=useFetcher<any>(),selected=useFetcher<any>();const [q,setQ]=useState('');const [page,setPage]=useState(0);
 const ids:string[]=multiple?(value||[]):value?[String(value)]:[];const selection=ids.join(',');
 const search=new URLSearchParams({context,q,page:String(page),size:'25',...(projectId?{projectId}:{})}).toString();
 useEffect(()=>{if(source)fetcher.load('/lookups/'+source+'?'+search);},[source,search]);
 useEffect(()=>{if(source&&selection)selected.load('/lookups/'+source+'?'+new URLSearchParams({context,ids:selection,size:'100',...(projectId?{projectId}:{})}));},[source,context,selection,projectId]);
 const options=fetcher.data?.items||[],labels=new Map<string,string>([...(selected.data?.items||[]),...options].map((item:any)=>[item.id,item.title]));
 return <div className="rounded-lg border p-3"><input className="input mb-2" aria-label={'Search '+fieldLabel} placeholder={'Search '+fieldLabel.toLowerCase()} value={q} onChange={e=>{setQ(e.target.value);setPage(0);}}/>
 {ids.length>0&&<div className="flex flex-wrap gap-2 mb-3">{ids.map(id=><button type="button" className="btn small" key={id} onClick={()=>onChange(multiple?ids.filter(x=>x!==id):null)} aria-label={'Remove '+(labels.get(id)||id)}>{labels.get(id)||id} ×</button>)}</div>}
 {multiple?<div className="multichoice">{options.map((item:any)=><label key={item.id}><Checkbox checked={ids.includes(item.id)} onCheckedChange={checked=>onChange(checked?[...ids,item.id]:ids.filter(id=>id!==item.id))}/>{item.title}</label>)}</div>:<Pick label={fieldLabel} value={value} onChange={v=>onChange(v||null)} options={[...new Map([...options,...(selected.data?.items||[])].map((item:any)=>[item.id,item])).values()].map((item:any)=>({value:item.id,label:item.title}))}/>}
 <div className="flex justify-between mt-2"><button type="button" className="btn small" disabled={page===0||fetcher.state!=='idle'} onClick={()=>setPage(page-1)}>Previous</button><span className="text-sm">{fetcher.state!=='idle'?'Loading…':'Page '+(page+1)}</span><button type="button" className="btn small" disabled={!fetcher.data?.hasNext||fetcher.state!=='idle'} onClick={()=>setPage(page+1)}>Next</button></div></div>;
}
export function EditorPage(){const {kind,item}=useLoaderData() as any;const session=useSession();const fetcher=useFetcher<any>();const specs=fields[kind]||[];const location=useLocation();const defaults=Object.fromEntries(specs.filter(f=>f.options).map(f=>[f.key,f.options![0]]));
 const [draft,setDraft]=useState<any>({...defaults,scope:'hierarchy',lessons:[],questions:[],...item});const [dirty,setDirty]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{setDraft({...defaults,scope:'hierarchy',lessons:[],questions:[],...item});setDirty(false);setError('');},[kind,item?.id]);
 useEffect(()=>{if(fetcher.data?.error)setDirty(true);},[fetcher.data]);
 const blocker=useBlocker(dirty&&fetcher.state==='idle');
 function change(key:string,value:any){setDraft((d:any)=>({...d,[key]:value,...(key==='projectId'?{ownerId:null,sprintId:null,dependencies:[]}:{}),...(key==='entityKind'?{entityId:null}:{})}));setDirty(true);}
 if(!allowed(session,kind,item?'update':'create')||!fields[kind]||!item&&noCreate.has(kind))return <RouteError message="Your role cannot perform this action."/>;
 function submit(e:React.FormEvent){e.preventDefault();setError('');for(const field of specs)if(field.required&&!draft[field.key]){setError(field.label+' is required.');return;}
 const body:any=Object.fromEntries(specs.filter(f=>draft[f.key]!==undefined&&!(f.key==='password'&&!draft[f.key])).map(f=>[f.key,draft[f.key]]));
 if(item)body.version=item.version;if(kind==='roles'&&!item)body.permissions={};if(kind==='users'&&!item&&!body.password){setError('A password is required for a new user.');return;}
 setDirty(false);fetcher.submit({body},{method:'post',encType:'application/json',action:location.pathname});
 }
 return <><Link className="btn ghost mb-4" to={item?'/'+kind+'/'+item.id:'/'+kind}><ArrowLeft size={15}/>Back</Link><div className="pageheading"><h1>{item?'Edit':'Create'} {label(kind)}</h1></div><div className="panel p-6 max-w-4xl"><form onSubmit={submit}><div className="form-grid">{specs.map(field=><div className={'field '+(['multi','textarea','lessons','questions'].includes(field.type||'')||field.source?'wide':'')} key={field.key}><label htmlFor={'field-'+field.key}>{field.label}{field.required?' *':''}</label>
 {field.source?<ReferenceField key={field.key+':'+(field.source==='parent'?draft.entityKind:field.source)+':'+(draft.projectId||'')} source={field.source==='parent'?draft.entityKind:field.source} context={kind} projectId={['ownerId','sprintId','dependencies'].includes(field.key)?draft.projectId:undefined} value={draft[field.key]} multiple={field.type==='multi'} onChange={v=>change(field.key,v)} fieldLabel={field.label}/>:
 field.type==='textarea'?<textarea className="input" id={'field-'+field.key} value={draft[field.key]||''} required={field.required} onChange={e=>change(field.key,e.target.value)}/>:
 field.type==='boolean'?<Checkbox id={'field-'+field.key} checked={!!draft[field.key]} onCheckedChange={v=>change(field.key,v===true)}/>:
 ['lessons','questions'].includes(field.type||'')?<StructuredFields type={field.type!} value={draft[field.key]||[]} onChange={v=>change(field.key,v)}/>:
 field.options?<Pick label={field.label} value={draft[field.key]} onChange={v=>change(field.key,v)} options={field.options.map(value=>({value,label:value}))}/>:
 <input className="input" id={'field-'+field.key} type={field.type||'text'} value={draft[field.key]??''} min={field.type==='number'?0:undefined} step={field.type==='number'?'any':undefined} required={field.required} onChange={e=>change(field.key,field.type==='number'?e.target.value===''?null:Number(e.target.value):e.target.value)}/>}
 </div>)}</div>{error&&<p className="error mt-4" role="alert">{error}</p>}<Feedback fetcher={fetcher}/><div className="flex justify-end gap-3 mt-6"><Link className="btn" to={item?'/'+kind+'/'+item.id:'/'+kind}>Cancel</Link><button className="btn primary" disabled={fetcher.state!=='idle'}>{fetcher.state!=='idle'?'Saving…':'Save'}</button></div></form></div>
 <AlertDialog open={blocker.state==='blocked'}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Discard unsaved changes?</AlertDialogTitle><AlertDialogDescription>Your changes have not been saved.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel onClick={()=>blocker.reset?.()}>Keep editing</AlertDialogCancel><AlertDialogAction onClick={()=>blocker.proceed?.()}>Discard changes</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
function StructuredFields({type,value,onChange}:{type:string;value:any[];onChange:(value:any[])=>void}){const lesson=type==='lessons';function update(index:number,patch:any){onChange(value.map((item,i)=>i===index?{...item,...patch}:item));}return <div>{value.map((item,i)=><div className="lesson" key={i}><input className="input mb-3" aria-label={(lesson?'Lesson':'Question')+' '+(i+1)} placeholder={lesson?'Lesson title':'Question'} value={lesson?item.title:item.prompt} onChange={e=>update(i,{[lesson?'title':'prompt']:e.target.value})} required/>{lesson?<textarea className="input" aria-label={'Lesson '+(i+1)+' content'} value={item.content} onChange={e=>update(i,{content:e.target.value})}/>:<>{item.options.map((option:string,j:number)=><input className="input mb-2" key={j} aria-label={'Question '+(i+1)+' option '+(j+1)} value={option} onChange={e=>update(i,{options:item.options.map((text:string,index:number)=>index===j?e.target.value:text)})} required/>)}<Pick label="Correct answer" value={String((item.answer??0)+1)} onChange={v=>update(i,{answer:Number(v)-1})} options={item.options.map((_:any,j:number)=>({value:String(j+1),label:'Correct answer: option '+(j+1)}))}/></>}<button type="button" className="btn ghost small mt-3" onClick={()=>onChange(value.filter((_,index)=>index!==i))}>Remove</button></div>)}<button type="button" className="btn" onClick={()=>onChange([...value,lesson?{title:'',content:''}:{prompt:'',options:['','',''],answer:0}])}><Plus size={14}/>Add {lesson?'lesson':'question'}</button></div>;}
function RolePermissions({item}:{item:Item}){const session=useSession(),fetcher=useFetcher<any>();const [permissions,setPermissions]=useState(item.permissions||{});useEffect(()=>setPermissions(item.permissions||{}),[item.id,item.version]);return <div className="detail-section"><h2 className="font-semibold mb-4">Module → submodule → permissions</h2><Table><TableHeader><TableRow><TableHead>Module / submodule</TableHead>{['create','read','update','delete'].map(action=><TableHead key={action} className="capitalize">{action}</TableHead>)}</TableRow></TableHeader><TableBody>{modules.map(module=><TableRow key={module.key}><TableCell><span className="block text-xs text-slate-500">{module.module}</span>{module.label}</TableCell>{['create','read','update','delete'].map(action=><TableCell key={action}><Checkbox aria-label={module.label+' '+action} disabled={!allowed(session,'roles','update')} checked={!!permissions[module.key]?.[action]} onCheckedChange={value=>setPermissions({...permissions,[module.key]:{...permissions[module.key],[action]:value===true}})}/></TableCell>)}</TableRow>)}</TableBody></Table>{allowed(session,'roles','update')&&<button className="btn primary mt-4" disabled={fetcher.state!=='idle'} onClick={()=>fetcher.submit({intent:'permissions',body:{permissions,version:item.version}},{method:'post',encType:'application/json'})}>Save permissions</button>}<Feedback fetcher={fetcher}/></div>;}
export function DetailPage(){const {kind,item}=useLoaderData() as any;const session=useSession();const fetcher=useFetcher<any>();const [confirm,setConfirm]=useState(false);const [status,setStatus]=useState(item.status);const [hours,setHours]=useState(item.actualHours||0);const [submission,setSubmission]=useState(item.submission||'');const [score,setScore]=useState(0);const [feedback,setFeedback]=useState('');const [answers,setAnswers]=useState<Record<number,number>>({});
 useEffect(()=>{setStatus(item.status);setHours(item.actualHours||0);setSubmission(item.submission||'');setAnswers({});},[item.id,item.version]);
 const simple=['tasks','bugs'].includes(kind)&&!item.canManage;const busy=fetcher.state!=='idle';
 function action(intent:string,body:any,extra:any={}){fetcher.submit({intent,body:{...body,version:item.version},...extra},{method:'post',encType:'application/json'});}
 return <><Link className="btn ghost mb-4" to={'/'+kind}><ArrowLeft size={15}/>{label(kind)}</Link><div className="panel p-6 max-w-5xl"><div className="eyebrow">{label(kind)}</div><h1 className="detail-title">{item.title}</h1><div className="mt-4"><Badge value={item.status}/></div><div className="detail-actions">{allowed(session,kind,'update')&&fields[kind]&&!simple&&<Link className="btn" to={'/'+kind+'/'+item.id+'/edit'}><Pencil size={15}/>Edit details</Link>}{allowed(session,kind,'delete')&&!['users','attendance','attempts','settings','audit'].includes(kind)&&<button className="btn danger" onClick={()=>setConfirm(true)}><Trash2 size={15}/>Delete</button>}</div>
 {kind==='projects'&&<div className="detail-actions">{allowed(session,'tasks')&&<Link className="btn" to={'/tasks?projectId='+item.id}>Project tasks</Link>}{allowed(session,'bugs')&&item.bugsEnabled&&<Link className="btn" to={'/bugs?projectId='+item.id}>Project bugs</Link>}</div>}
 <div className="detail-meta">{Object.entries(item.labels||{}).map(([key,value])=><div key={key}><span>{key.replace(/Id$/,'').replace(/([A-Z])/g,' $1')}</span><p>{String(value)}</p></div>)}{['priority','dueDate','startDate','estimatedHours','actualHours','workingHours','score','checkIn','checkOut','position','email','scope','client','technology','budget','capacity'].filter(key=>item[key]!==undefined&&item[key]!=='').map(key=><div key={key}><span>{key.replace(/([A-Z])/g,' $1')}</span><p>{String(item[key])}</p></div>)}</div>
 {['description','goal','expectedOutput','mitigation','yesterday','today','blockers','wentWell','improve','actions','feedback'].filter(key=>item[key]).map(key=><div className="detail-section" key={key}><h3 className="capitalize">{key.replace(/([A-Z])/g,' $1')}</h3><p className="detail-copy">{item[key]}</p></div>)}
 {kind==='settings'&&<div className="stats">{Object.keys(item).filter(k=>k.endsWith('Weight')).map(key=><div className="stat" key={key}><p className="capitalize">{key.replace('Weight','')}</p><p className="text-xl mt-2">{item[key]}%</p></div>)}</div>}
 {kind==='roles'&&<RolePermissions item={item}/>}
 {['tasks','bugs'].includes(kind)&&allowed(session,kind,'update')&&<div className="detail-section"><h3>Update progress</h3><div className="form-grid"><label className="field">Status<Pick label="Status" value={status} onChange={setStatus} options={statuses.filter(s=>!simple||s!=='Done').map(value=>({value,label:value}))}/></label><label className="field">Actual hours<input className="input" type="number" min={0} step="0.25" value={hours} onChange={e=>setHours(Number(e.target.value))}/></label></div><button className="btn primary mt-4" disabled={busy} onClick={()=>action('progress',{status,actualHours:hours})}>Save progress</button></div>}
 {kind==='assessments'&&item.status==='Published'&&allowed(session,'attempts','create')&&<div className="detail-section"><h3>Take assessment</h3>{(item.questions||[]).map((q:any,i:number)=><div className="lesson" key={i}><h4>{i+1}. {q.prompt}</h4><Pick label={q.prompt} value={answers[i]===undefined?'':String(answers[i]+1)} onChange={value=>setAnswers({...answers,[i]:Number(value)-1})} options={q.options.map((text:string,j:number)=>({value:String(j+1),label:text}))}/></div>)}<button className="btn primary" disabled={busy||Object.keys(answers).length!==(item.questions||[]).length} onClick={()=>action('submit',{answers:item.questions.map((_:any,i:number)=>answers[i])})}>Submit assessment</button>{fetcher.data?.record?.score!==undefined&&<p role="status" className="mt-4">Result: {fetcher.data.record.score}% · {fetcher.data.record.status}</p>}</div>}
 {kind==='assignments'&&item.ownerId===session.user.id&&allowed(session,kind,'update')&&<div className="detail-section"><h3>Your submission</h3><textarea className="input" aria-label="Submission" value={submission} onChange={e=>setSubmission(e.target.value)}/><button className="btn primary mt-4" disabled={busy||!submission.trim()} onClick={()=>action('submit',{submission})}>Submit work</button></div>}
 {kind==='assignments'&&item.submission&&<div className="detail-section"><h3>Submitted work</h3><p className="detail-copy">{item.submission}</p>{item.ownerId!==session.user.id&&item.status==='Submitted'&&allowed(session,kind,'update')&&<><label className="field mt-4">Score (0–100)<input className="input" type="number" min={0} max={100} value={score} onChange={e=>setScore(Number(e.target.value))}/></label><label className="field mt-4">Feedback<textarea className="input" value={feedback} onChange={e=>setFeedback(e.target.value)}/></label><button className="btn primary mt-4" disabled={busy} onClick={()=>action('evaluate',{score,feedback})}>Save evaluation</button></>}</div>}
 {['courses','enrollments'].includes(kind)&&<CourseProgress kind={kind} item={item}/>}
 {kind==='notifications'&&item.ownerId===session.user.id&&item.status==='Unread'&&allowed(session,kind,'update')&&<button className="btn" disabled={busy} onClick={()=>action('read',{})}>Mark as read</button>}
 <Feedback fetcher={fetcher}/>{['projects','tasks','bugs','assignments','courses','sprints'].includes(kind)&&<RelatedPanels kind={kind} item={item}/>}
 </div><AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete {item.title}?</AlertDialogTitle><AlertDialogDescription>Referenced records must be archived instead.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();action('delete',{});}}>Delete</AlertDialogAction></AlertDialogFooter><Feedback fetcher={fetcher}/></AlertDialogContent></AlertDialog></>;
}
function CourseProgress({kind,item}:{kind:string;item:Item}){const session=useSession();const courseFetcher=useFetcher<any>(),enrollmentFetcher=useFetcher<any>(),complete=useFetcher<any>();
 useEffect(()=>{if(kind==='enrollments'&&allowed(session,'courses'))courseFetcher.load('/related/courses/'+item.courseId);if(kind==='courses'&&allowed(session,'enrollments'))enrollmentFetcher.load('/related/enrollments?'+new URLSearchParams({courseId:item.id,ownerId:session.user.id,size:'1'}));},[kind,item.id,item.version]);
 const course=kind==='courses'?item:courseFetcher.data;const enrollment=kind==='enrollments'?item:enrollmentFetcher.data?.items?.[0];
 return <div className="detail-section"><h3>Lessons</h3>{course?.lessons?.map((lesson:any,i:number)=><div className="lesson" key={i}><h4>{i+1}. {lesson.title}</h4><p className="detail-copy">{lesson.content}</p>{enrollment&&allowed(session,'enrollments','update')&&<button className="btn small mt-4" disabled={complete.state!=='idle'||enrollment.completedLessons?.map(Number).includes(i)} onClick={()=>complete.submit({intent:'lesson',lesson:i,body:{version:enrollment.version}},{method:'post',encType:'application/json',action:'/enrollments/'+enrollment.id})}>{enrollment.completedLessons?.map(Number).includes(i)?'Completed':'Mark complete'}</button>}</div>)}{!course&&<p className="subtitle">Course details are unavailable or loading.</p>}<Feedback fetcher={complete}/></div>;
}
function RelatedPanels({kind,item}:{kind:string;item:Item}){const session=useSession();const comments=useFetcher<any>(),files=useFetcher<any>(),post=useFetcher<any>(),upload=useFetcher<any>();const [page,setPage]=useState(0),[filePage,setFilePage]=useState(0),[text,setText]=useState('');
 const query=new URLSearchParams({entityKind:kind,entityId:item.id,size:'25'});
 useEffect(()=>{if(allowed(session,'comments'))comments.load('/record-comments?'+query+'&page='+page);},[kind,item.id,page,item.version,post.data]);
 useEffect(()=>{if(allowed(session,'documents'))files.load('/record-files?'+query+'&page='+filePage);},[kind,item.id,filePage,upload.data]);
 useEffect(()=>{if(post.data?.message)setText('');},[post.data]);
 return <>{allowed(session,'comments')&&<div className="detail-section"><h3>Discussion</h3>{comments.data?.items?.map((comment:any)=><div className="activity" key={comment.id}><div><Link className="font-medium" to={'/comments/'+comment.id}>{comment.labels?.ownerId||'Comment'}</Link><p className="detail-copy">{comment.description}</p></div></div>)}<div className="flex gap-2 mt-3"><button className="btn small" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><button className="btn small" disabled={!comments.data?.hasNext} onClick={()=>setPage(page+1)}>Next</button></div></div>}
 {allowed(session,'comments','create')&&<div className="detail-section"><h3>Add comment</h3><textarea className="input" aria-label="Comment" value={text} onChange={e=>setText(e.target.value)}/><button className="btn mt-3" disabled={!text.trim()||post.state!=='idle'} onClick={()=>post.submit({body:{title:text.slice(0,100),description:text,entityKind:kind,entityId:item.id,status:'Active'}},{method:'post',action:'/comments/new',encType:'application/json'})}>Post comment</button><Feedback fetcher={post}/></div>}
 {allowed(session,'documents')&&<div className="detail-section"><h3>Attachments</h3>{files.data?.items?.map((file:any)=><a key={file.id} className="source-link mb-3" href={'/api/v1/files/'+file.id}><Download size={14}/>{file.filename}</a>)}<div className="flex gap-2"><button className="btn small" disabled={filePage===0} onClick={()=>setFilePage(filePage-1)}>Previous</button><button className="btn small" disabled={!files.data?.hasNext} onClick={()=>setFilePage(filePage+1)}>Next</button></div></div>}
 {allowed(session,'documents','create')&&<upload.Form method="post" encType="multipart/form-data" action={'/'+kind+'/'+item.id} className="detail-section"><label className="field">Upload file (up to 10 MB)<input className="input" type="file" name="file" accept=".pdf,.png,.jpg,.jpeg,.txt,.csv,.docx,.xlsx,.pptx,.mp4,.webm" required/></label><button className="btn mt-3" disabled={upload.state!=='idle'}>Upload</button><Feedback fetcher={upload}/></upload.Form>}</>;
}
